### ISSUE TITLE
events+music+{finish.js}

### ISSUE THREAD

**Issue by coco66688** [ckt1031/DraconianBot#10]
(node:1322) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'send' of undefined
    at module.exports (/home/runner/AssistantRobot/events/music/finish.js:2:18)
    at DisTube.emit (events.js:314:20)
    at DisTube.EventEmitter.emit (domain.js:483:12)
    at DisTube._handleSongFinish (/home/runner/AssistantRobot/node_modules/distube/src/DisTube.js:936:35)
    at StreamDispatcher.<anonymous> (/home/runner/AssistantRobot/node_modules/distube/src/DisTube.js:904:34)
    at StreamDispatcher.emit (events.js:326:22)
    at StreamDispatcher.EventEmitter.emit (domain.js:483:12)
    at finishMaybe (_stream_writable.js:639:14)
    at _stream_writable.js:616:5
    at StreamDispatcher._final (/home/runner/AssistantRobot/node_modules/discord.js/src/client/voice/dispatcher/StreamDispatcher.js:248:5)
(node:1322) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1322) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ckt1031** [comment]
I directly deleted that file cuz its useless for the queue within autoplay.
