### ISSUE TITLE
Please help, it gives an error while i try to start it

### ISSUE THREAD

**Issue by ShadowPro1** [ckt1031/DraconianBot#17]
Well idk what type of bug is it but its not starting

**To Reproduce**

I just started it and gave me this error

error:
Command Loaded weather.js
internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module './handlers/dbl-loader.js'
Require stack:
- /home/container/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at /home/container/index.js:35:2
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/container/index.js:34:57)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/container/index.js' ]
![image](https://user-images.githubusercontent.com/86128177/122608228-832da800-d084-11eb-9b31-27425b2a8694.png)

**Comment by bymylonely** [comment]
same problem

**Comment by EricZil** [comment]
That means that you didn't install successfully `node.js`. 
Try this by fixing this problem >`npm ci`

**Comment by ckt1031** [comment]
Issue Solved
